spring:
  datasource:
    url: jdbc:postgresql://61.99.10.111:5432/MERO_DB
    username: postgres
    password: tjdgns123..
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true